"""Built-in Windows PE binary classifier index."""

from __future__ import annotations

WIN_BINARY_ENTRIES: list[dict] = [
    {
        "id": "openssl",
        "product_name_contains": ["OpenSSL"],
        "company_contains": ["OpenSSL"],
        "name": "openssl",
        "cpe_template": "cpe:2.3:a:openssl:openssl:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/openssl@{version}",
    },
    {
        "id": "libressl",
        "product_name_contains": ["LibreSSL"],
        "company_contains": [],
        "name": "libressl",
        "cpe_template": "cpe:2.3:a:openbsd:libressl:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/libressl@{version}",
    },
    {
        "id": "mbedtls",
        "product_name_contains": ["Mbed TLS", "mbed TLS", "mbedTLS"],
        "company_contains": ["ARM", "Mbed"],
        "name": "mbedtls",
        "cpe_template": "cpe:2.3:a:arm:mbed_tls:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/mbedtls@{version}",
    },
    {
        "id": "curl",
        "product_name_contains": ["curl", "libcurl"],
        "company_contains": ["curl", "Daniel Stenberg", "haxx"],
        "name": "curl",
        "cpe_template": "cpe:2.3:a:haxx:curl:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/curl@{version}",
    },
    {
        "id": "libssh2",
        "product_name_contains": ["libssh2"],
        "company_contains": ["libssh2", "Sara Golemon"],
        "name": "libssh2",
        "cpe_template": "cpe:2.3:a:libssh2:libssh2:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/libssh2@{version}",
    },
    {
        "id": "nghttp2",
        "product_name_contains": ["nghttp2"],
        "company_contains": [],
        "name": "nghttp2",
        "cpe_template": "cpe:2.3:a:nghttp2:nghttp2:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/nghttp2@{version}",
    },
    {
        "id": "zlib",
        "product_name_contains": ["zlib"],
        "company_contains": ["Gailly", "Adler", "zlib"],
        "name": "zlib",
        "cpe_template": "cpe:2.3:a:zlib:zlib:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/zlib@{version}",
    },
    {
        "id": "bzip2",
        "product_name_contains": ["bzip2", "libbzip2"],
        "company_contains": [],
        "name": "bzip2",
        "cpe_template": "cpe:2.3:a:bzip:bzip2:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/bzip2@{version}",
    },
    {
        "id": "xz_utils",
        "product_name_contains": ["XZ Utils", "liblzma"],
        "company_contains": [],
        "name": "xz-utils",
        "cpe_template": "cpe:2.3:a:tukaani:xz:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/xz-utils@{version}",
    },
    {
        "id": "python_runtime",
        "product_name_contains": ["Python"],
        "company_contains": ["Python Software Foundation"],
        "name": "python",
        "cpe_template": "cpe:2.3:a:python:python:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/python@{version}",
    },
    {
        "id": "nodejs",
        "product_name_contains": ["Node.js"],
        "company_contains": ["Node.js", "OpenJS Foundation", "Joyent"],
        "name": "nodejs",
        "cpe_template": "cpe:2.3:a:nodejs:node.js:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/nodejs@{version}",
    },
    {
        "id": "ruby",
        "product_name_contains": ["Ruby"],
        "company_contains": ["Ruby", "Yukihiro Matsumoto"],
        "name": "ruby",
        "cpe_template": "cpe:2.3:a:ruby-lang:ruby:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/ruby@{version}",
    },
    {
        "id": "perl",
        "product_name_contains": ["Perl"],
        "company_contains": ["ActiveState", "Strawberry Perl", "Perl"],
        "name": "perl",
        "cpe_template": "cpe:2.3:a:perl:perl:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/perl@{version}",
    },
    {
        "id": "sqlite",
        "product_name_contains": ["SQLite"],
        "company_contains": ["SQLite", "Hwaci"],
        "name": "sqlite",
        "cpe_template": "cpe:2.3:a:sqlite:sqlite:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/sqlite@{version}",
    },
    {
        "id": "libpng",
        "product_name_contains": ["libpng"],
        "company_contains": ["libpng", "Glenn Randers"],
        "name": "libpng",
        "cpe_template": "cpe:2.3:a:libpng:libpng:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/libpng@{version}",
    },
    {
        "id": "libjpeg",
        "product_name_contains": ["libjpeg", "libjpeg-turbo", "Independent JPEG Group"],
        "company_contains": [],
        "name": "libjpeg",
        "cpe_template": "cpe:2.3:a:ijg:libjpeg:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/libjpeg@{version}",
    },
    {
        "id": "libwebp",
        "product_name_contains": ["WebP", "libwebp"],
        "company_contains": ["Google"],
        "name": "libwebp",
        "cpe_template": "cpe:2.3:a:webmproject:libwebp:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/libwebp@{version}",
    },
    {
        "id": "libxml2",
        "product_name_contains": ["libxml2"],
        "company_contains": ["Daniel Veillard", "xmlsoft"],
        "name": "libxml2",
        "cpe_template": "cpe:2.3:a:xmlsoft:libxml2:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/libxml2@{version}",
    },
    {
        "id": "expat",
        "product_name_contains": ["Expat", "libexpat"],
        "company_contains": ["Expat"],
        "name": "expat",
        "cpe_template": "cpe:2.3:a:libexpat:expat:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/expat@{version}",
    },
    {
        "id": "putty",
        "product_name_contains": ["PuTTY"],
        "company_contains": ["Simon Tatham", "PuTTY"],
        "name": "putty",
        "cpe_template": "cpe:2.3:a:putty:putty:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/putty@{version}",
    },
    {
        "id": "winscp",
        "product_name_contains": ["WinSCP"],
        "company_contains": ["Martin Prikryl", "WinSCP"],
        "name": "winscp",
        "cpe_template": "cpe:2.3:a:winscp:winscp:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/winscp@{version}",
    },
    {
        "id": "git",
        "product_name_contains": ["Git"],
        "company_contains": ["The Git Development Community", "Johannes Schindelin"],
        "name": "git",
        "cpe_template": "cpe:2.3:a:git-scm:git:{version}:*:*:*:*:*:*:*",
        "purl_template": "pkg:generic/git@{version}",
    },
]
